{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "e245e390-2bf9-44e7-8461-95933e92f1d7",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Python executable: /home/yeray/miniconda3/envs/tfg-py3.12/bin/python\n",
      "1.26.4\n",
      "Directorio actual: /home/yeray/TFG-Home-Credit-Default-Risk/JUPYTER_NOTEBOOKS\n",
      "<class 'pandas.core.frame.DataFrame'>\n",
      "RangeIndex: 307511 entries, 0 to 307510\n",
      "Columns: 307 entries, TARGET to WALLSMATERIAL_MODE_Wooden\n",
      "dtypes: bool(127), float64(138), int64(42)\n",
      "memory usage: 459.5 MB\n",
      "None\n",
      "(307511, 307)\n"
     ]
    }
   ],
   "source": [
    "#Celda para librer√≠as\n",
    "import sklearn as sk\n",
    "import sys\n",
    "print(\"Python executable:\", sys.executable)\n",
    "\n",
    "import matplotlib as plt\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "import pandas as pd\n",
    "import seaborn as sns\n",
    "import numpy as np\n",
    "from sklearn.model_selection import train_test_split, cross_val_score\n",
    "\n",
    "import optuna\n",
    "from sklearn.model_selection import StratifiedKFold\n",
    "from sklearn.metrics import roc_auc_score\n",
    "\n",
    "#XGBoost\n",
    "from xgboost import XGBClassifier\n",
    "\n",
    "\n",
    "\n",
    "from hyperopt import hp, fmin, tpe, STATUS_OK, Trials\n",
    "from sklearn.model_selection import cross_val_score\n",
    "\n",
    "\n",
    "import json\n",
    "\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "print(np.__version__)\n",
    "from ydata_profiling import ProfileReport\n",
    "import os\n",
    "print(\"Directorio actual:\", os.getcwd())\n",
    "\n",
    "# Have all columns appear when dataframes are displayed.\n",
    "pd.set_option('display.max_columns', None) \n",
    "# Have 100 rows appear when a dataframe is displayed\n",
    "pd.set_option('display.max_rows', 500)\n",
    "# Display dimensions whenever a dataframe is printed out.\n",
    "pd.set_option('display.show_dimensions', True)\n",
    "\n",
    "#Importando los datos\n",
    "\n",
    "app_train_def = pd.read_csv(r'/home/yeray/TFG-Home-Credit-Default-Risk/JUPYTER_NOTEBOOKS/DATA/application_train_preprocesado_definitivo_v1.csv')\n",
    "#app_train_def_2 = pd.read_csv(r'/home/yeray/TFG-Home-Credit-Default-Risk/JUPYTER_NOTEBOOKS/DATA/application_train_preprocesado_definitivo_v2.csv')\n",
    "#app_train_def_3 = pd.read_csv(r'/home/yeray/TFG-Home-Credit-Default-Risk/JUPYTER_NOTEBOOKS/DATA/application_train_preprocesado_definitivo_v3.csv')\n",
    "#app_train_def_4 = pd.read_csv(r'/home/yeray/TFG-Home-Credit-Default-Risk/JUPYTER_NOTEBOOKS/DATA/application_train_preprocesado_definitivo_v4.csv')\n",
    "#app_train_def_5 = pd.read_csv(r'/home/yeray/TFG-Home-Credit-Default-Risk/JUPYTER_NOTEBOOKS/DATA/application_train_preprocesado_definitivo_v5.csv')\n",
    "\n",
    "print(app_train_def.info())\n",
    "print(app_train_def.shape)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "d040e960-9702-4d99-afa2-34196f1f194f",
   "metadata": {},
   "outputs": [],
   "source": [
    "X = app_train_def.drop(columns = ['TARGET'])\n",
    "y = app_train_def['TARGET']\n",
    "X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)\n",
    "\n",
    "X_train.columns = X_train.columns.str.replace('[^A-Za-z0-9_]+', '', regex=True)\n",
    "X_test.columns = X_test.columns.str.replace('[^A-Za-z0-9_]+', '', regex=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "89f6a6bd-9539-4469-9703-c4a73d78d699",
   "metadata": {},
   "outputs": [],
   "source": [
    "def objective(trial):\n",
    "    params = {\n",
    "        \"n_estimators\": trial.suggest_int(\"n_estimators\", 900, 1800, step=50),\n",
    "        \"max_bin\": trial.suggest_int(\"max_bin\", 200, 400, step=10),\n",
    "        \"learning_rate\": trial.suggest_float(\"learning_rate\", 0.01, 0.03, log=True),\n",
    "        \"max_depth\": trial.suggest_int(\"max_depth\", 5, 10),\n",
    "        \"gamma\": trial.suggest_float(\"gamma\", 0, 3),\n",
    "        \"min_child_weight\": trial.suggest_int(\"min_child_weight\", 12, 24),\n",
    "        \"subsample\": trial.suggest_float(\"subsample\", 0.6, 0.95),\n",
    "        \"colsample_bytree\": trial.suggest_float(\"colsample_bytree\", 0.4, 0.8),\n",
    "        \"n_jobs\": trial.suggest_int(\"n_jobs\", 1, 10),\n",
    "        \"reg_alpha\": trial.suggest_float(\"reg_alpha\", 1e-8, 1.0, log=True),\n",
    "        \"reg_lambda\": trial.suggest_float(\"reg_lambda\", 1e-8, 10.0, log=True),\n",
    "        \"tree_method\": trial.suggest_categorical(\"tree_method\", [\"auto\", \"hist\"]),\n",
    "        \"scale_pos_weight\": trial.suggest_float(\"scale_pos_weight\", 1.0, 3.0),\n",
    "    }\n",
    "    model = XGBClassifier(\n",
    "        **params,\n",
    "        objective=\"binary:logistic\",\n",
    "        eval_metric=\"auc\",\n",
    "        use_label_encoder=False,\n",
    "        random_state=42\n",
    "    )\n",
    "\n",
    "    cv=StratifiedKFold(n_splits=5, shuffle=True, random_state=42)\n",
    "    scores = cross_val_score(model,X_train, y_train, scoring='roc_auc', cv=cv)\n",
    "\n",
    "    return scores.mean()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "533c5cb0-c2de-4021-bd7b-9f255de7f864",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[I 2025-02-24 12:13:35,728] A new study created in memory with name: no-name-e6fbdc80-48a2-4d6b-8ff9-5e5313398aba\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "50c06644a13e458db4433dba9c472aac",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "  0%|          | 0/50 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[W 2025-02-24 12:14:11,061] Trial 0 failed with parameters: {'n_estimators': 1100, 'max_bin': 350, 'learning_rate': 0.01076149921794883, 'max_depth': 5, 'gamma': 2.2972476328024736, 'min_child_weight': 24, 'subsample': 0.9001627622266781, 'colsample_bytree': 0.5971742312777, 'n_jobs': 1, 'reg_alpha': 2.2741230956838323e-07, 'reg_lambda': 1.3479724732454081e-06, 'tree_method': 'gpu_hist', 'scale_pos_weight': 1.5136723633812077} because of the following error: ValueError('\\nAll the 5 fits failed.\\nIt is very likely that your model is misconfigured.\\nYou can try to debug the error by setting error_score=\\'raise\\'.\\n\\nBelow are more details about the failures:\\n--------------------------------------------------------------------------------\\n1 fits failed with the following error:\\nTraceback (most recent call last):\\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/sklearn/model_selection/_validation.py\", line 729, in _fit_and_score\\n    estimator.fit(X_train, y_train, **fit_params)\\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\\n    return func(**kwargs)\\n           ^^^^^^^^^^^^^^\\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/sklearn.py\", line 1531, in fit\\n    self._Booster = train(\\n                    ^^^^^^\\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\\n    return func(**kwargs)\\n           ^^^^^^^^^^^^^^\\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/training.py\", line 181, in train\\n    bst.update(dtrain, iteration=i, fobj=obj)\\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 2100, in update\\n    _check_call(\\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 284, in _check_call\\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\\nxgboost.core.XGBoostError: [12:13:43] /workspace/src/tree/updater_gpu_hist.cu:861: Exception in gpu_hist: [12:13:43] /workspace/src/tree/updater_gpu_hist.cu:867: Check failed: ctx_->Ordinal() >= 0 (-1 vs. 0) : Must have at least one device\\nStack trace:\\n  [bt] (0) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7fe3bee99cbc]\\n  [bt] (1) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2c55d) [0x7fe3bf99855d]\\n  [bt] (2) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2ca04) [0x7fe3bf998a04]\\n  [bt] (3) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x57f526) [0x7fe3bf1eb526]\\n  [bt] (4) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5808f4) [0x7fe3bf1ec8f4]\\n  [bt] (5) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5cb1f8) [0x7fe3bf2371f8]\\n  [bt] (6) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterUpdateOneIter+0x6f) [0x7fe3beda352f]\\n  [bt] (7) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0xa052) [0x7fe4c8bf6052]\\n  [bt] (8) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0x8925) [0x7fe4c8bf4925]\\n\\n\\n\\nStack trace:\\n  [bt] (0) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7fe3bee99cbc]\\n  [bt] (1) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2cbd4) [0x7fe3bf998bd4]\\n  [bt] (2) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x57f526) [0x7fe3bf1eb526]\\n  [bt] (3) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5808f4) [0x7fe3bf1ec8f4]\\n  [bt] (4) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5cb1f8) [0x7fe3bf2371f8]\\n  [bt] (5) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterUpdateOneIter+0x6f) [0x7fe3beda352f]\\n  [bt] (6) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0xa052) [0x7fe4c8bf6052]\\n  [bt] (7) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0x8925) [0x7fe4c8bf4925]\\n  [bt] (8) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xde) [0x7fe4c8bf506e]\\n\\n\\n\\n--------------------------------------------------------------------------------\\n1 fits failed with the following error:\\nTraceback (most recent call last):\\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/sklearn/model_selection/_validation.py\", line 729, in _fit_and_score\\n    estimator.fit(X_train, y_train, **fit_params)\\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\\n    return func(**kwargs)\\n           ^^^^^^^^^^^^^^\\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/sklearn.py\", line 1531, in fit\\n    self._Booster = train(\\n                    ^^^^^^\\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\\n    return func(**kwargs)\\n           ^^^^^^^^^^^^^^\\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/training.py\", line 181, in train\\n    bst.update(dtrain, iteration=i, fobj=obj)\\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 2100, in update\\n    _check_call(\\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 284, in _check_call\\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\\nxgboost.core.XGBoostError: [12:13:50] /workspace/src/tree/updater_gpu_hist.cu:861: Exception in gpu_hist: [12:13:50] /workspace/src/tree/updater_gpu_hist.cu:867: Check failed: ctx_->Ordinal() >= 0 (-1 vs. 0) : Must have at least one device\\nStack trace:\\n  [bt] (0) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7fe3bee99cbc]\\n  [bt] (1) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2c55d) [0x7fe3bf99855d]\\n  [bt] (2) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2ca04) [0x7fe3bf998a04]\\n  [bt] (3) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x57f526) [0x7fe3bf1eb526]\\n  [bt] (4) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5808f4) [0x7fe3bf1ec8f4]\\n  [bt] (5) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5cb1f8) [0x7fe3bf2371f8]\\n  [bt] (6) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterUpdateOneIter+0x6f) [0x7fe3beda352f]\\n  [bt] (7) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0xa052) [0x7fe4c8bf6052]\\n  [bt] (8) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0x8925) [0x7fe4c8bf4925]\\n\\n\\n\\nStack trace:\\n  [bt] (0) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7fe3bee99cbc]\\n  [bt] (1) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2cbd4) [0x7fe3bf998bd4]\\n  [bt] (2) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x57f526) [0x7fe3bf1eb526]\\n  [bt] (3) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5808f4) [0x7fe3bf1ec8f4]\\n  [bt] (4) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5cb1f8) [0x7fe3bf2371f8]\\n  [bt] (5) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterUpdateOneIter+0x6f) [0x7fe3beda352f]\\n  [bt] (6) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0xa052) [0x7fe4c8bf6052]\\n  [bt] (7) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0x8925) [0x7fe4c8bf4925]\\n  [bt] (8) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xde) [0x7fe4c8bf506e]\\n\\n\\n\\n--------------------------------------------------------------------------------\\n1 fits failed with the following error:\\nTraceback (most recent call last):\\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/sklearn/model_selection/_validation.py\", line 729, in _fit_and_score\\n    estimator.fit(X_train, y_train, **fit_params)\\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\\n    return func(**kwargs)\\n           ^^^^^^^^^^^^^^\\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/sklearn.py\", line 1531, in fit\\n    self._Booster = train(\\n                    ^^^^^^\\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\\n    return func(**kwargs)\\n           ^^^^^^^^^^^^^^\\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/training.py\", line 181, in train\\n    bst.update(dtrain, iteration=i, fobj=obj)\\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 2100, in update\\n    _check_call(\\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 284, in _check_call\\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\\nxgboost.core.XGBoostError: [12:13:57] /workspace/src/tree/updater_gpu_hist.cu:861: Exception in gpu_hist: [12:13:57] /workspace/src/tree/updater_gpu_hist.cu:867: Check failed: ctx_->Ordinal() >= 0 (-1 vs. 0) : Must have at least one device\\nStack trace:\\n  [bt] (0) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7fe3bee99cbc]\\n  [bt] (1) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2c55d) [0x7fe3bf99855d]\\n  [bt] (2) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2ca04) [0x7fe3bf998a04]\\n  [bt] (3) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x57f526) [0x7fe3bf1eb526]\\n  [bt] (4) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5808f4) [0x7fe3bf1ec8f4]\\n  [bt] (5) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5cb1f8) [0x7fe3bf2371f8]\\n  [bt] (6) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterUpdateOneIter+0x6f) [0x7fe3beda352f]\\n  [bt] (7) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0xa052) [0x7fe4c8bf6052]\\n  [bt] (8) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0x8925) [0x7fe4c8bf4925]\\n\\n\\n\\nStack trace:\\n  [bt] (0) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7fe3bee99cbc]\\n  [bt] (1) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2cbd4) [0x7fe3bf998bd4]\\n  [bt] (2) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x57f526) [0x7fe3bf1eb526]\\n  [bt] (3) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5808f4) [0x7fe3bf1ec8f4]\\n  [bt] (4) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5cb1f8) [0x7fe3bf2371f8]\\n  [bt] (5) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterUpdateOneIter+0x6f) [0x7fe3beda352f]\\n  [bt] (6) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0xa052) [0x7fe4c8bf6052]\\n  [bt] (7) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0x8925) [0x7fe4c8bf4925]\\n  [bt] (8) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xde) [0x7fe4c8bf506e]\\n\\n\\n\\n--------------------------------------------------------------------------------\\n1 fits failed with the following error:\\nTraceback (most recent call last):\\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/sklearn/model_selection/_validation.py\", line 729, in _fit_and_score\\n    estimator.fit(X_train, y_train, **fit_params)\\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\\n    return func(**kwargs)\\n           ^^^^^^^^^^^^^^\\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/sklearn.py\", line 1531, in fit\\n    self._Booster = train(\\n                    ^^^^^^\\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\\n    return func(**kwargs)\\n           ^^^^^^^^^^^^^^\\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/training.py\", line 181, in train\\n    bst.update(dtrain, iteration=i, fobj=obj)\\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 2100, in update\\n    _check_call(\\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 284, in _check_call\\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\\nxgboost.core.XGBoostError: [12:14:04] /workspace/src/tree/updater_gpu_hist.cu:861: Exception in gpu_hist: [12:14:04] /workspace/src/tree/updater_gpu_hist.cu:867: Check failed: ctx_->Ordinal() >= 0 (-1 vs. 0) : Must have at least one device\\nStack trace:\\n  [bt] (0) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7fe3bee99cbc]\\n  [bt] (1) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2c55d) [0x7fe3bf99855d]\\n  [bt] (2) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2ca04) [0x7fe3bf998a04]\\n  [bt] (3) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x57f526) [0x7fe3bf1eb526]\\n  [bt] (4) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5808f4) [0x7fe3bf1ec8f4]\\n  [bt] (5) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5cb1f8) [0x7fe3bf2371f8]\\n  [bt] (6) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterUpdateOneIter+0x6f) [0x7fe3beda352f]\\n  [bt] (7) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0xa052) [0x7fe4c8bf6052]\\n  [bt] (8) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0x8925) [0x7fe4c8bf4925]\\n\\n\\n\\nStack trace:\\n  [bt] (0) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7fe3bee99cbc]\\n  [bt] (1) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2cbd4) [0x7fe3bf998bd4]\\n  [bt] (2) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x57f526) [0x7fe3bf1eb526]\\n  [bt] (3) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5808f4) [0x7fe3bf1ec8f4]\\n  [bt] (4) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5cb1f8) [0x7fe3bf2371f8]\\n  [bt] (5) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterUpdateOneIter+0x6f) [0x7fe3beda352f]\\n  [bt] (6) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0xa052) [0x7fe4c8bf6052]\\n  [bt] (7) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0x8925) [0x7fe4c8bf4925]\\n  [bt] (8) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xde) [0x7fe4c8bf506e]\\n\\n\\n\\n--------------------------------------------------------------------------------\\n1 fits failed with the following error:\\nTraceback (most recent call last):\\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/sklearn/model_selection/_validation.py\", line 729, in _fit_and_score\\n    estimator.fit(X_train, y_train, **fit_params)\\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\\n    return func(**kwargs)\\n           ^^^^^^^^^^^^^^\\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/sklearn.py\", line 1531, in fit\\n    self._Booster = train(\\n                    ^^^^^^\\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\\n    return func(**kwargs)\\n           ^^^^^^^^^^^^^^\\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/training.py\", line 181, in train\\n    bst.update(dtrain, iteration=i, fobj=obj)\\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 2100, in update\\n    _check_call(\\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 284, in _check_call\\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\\nxgboost.core.XGBoostError: [12:14:11] /workspace/src/tree/updater_gpu_hist.cu:861: Exception in gpu_hist: [12:14:11] /workspace/src/tree/updater_gpu_hist.cu:867: Check failed: ctx_->Ordinal() >= 0 (-1 vs. 0) : Must have at least one device\\nStack trace:\\n  [bt] (0) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7fe3bee99cbc]\\n  [bt] (1) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2c55d) [0x7fe3bf99855d]\\n  [bt] (2) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2ca04) [0x7fe3bf998a04]\\n  [bt] (3) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x57f526) [0x7fe3bf1eb526]\\n  [bt] (4) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5808f4) [0x7fe3bf1ec8f4]\\n  [bt] (5) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5cb1f8) [0x7fe3bf2371f8]\\n  [bt] (6) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterUpdateOneIter+0x6f) [0x7fe3beda352f]\\n  [bt] (7) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0xa052) [0x7fe4c8bf6052]\\n  [bt] (8) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0x8925) [0x7fe4c8bf4925]\\n\\n\\n\\nStack trace:\\n  [bt] (0) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7fe3bee99cbc]\\n  [bt] (1) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2cbd4) [0x7fe3bf998bd4]\\n  [bt] (2) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x57f526) [0x7fe3bf1eb526]\\n  [bt] (3) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5808f4) [0x7fe3bf1ec8f4]\\n  [bt] (4) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5cb1f8) [0x7fe3bf2371f8]\\n  [bt] (5) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterUpdateOneIter+0x6f) [0x7fe3beda352f]\\n  [bt] (6) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0xa052) [0x7fe4c8bf6052]\\n  [bt] (7) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0x8925) [0x7fe4c8bf4925]\\n  [bt] (8) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xde) [0x7fe4c8bf506e]\\n\\n\\n').\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 197, in _run_trial\n",
      "    value_or_values = func(trial)\n",
      "                      ^^^^^^^^^^^\n",
      "  File \"/tmp/ipykernel_40663/2765064930.py\", line 26, in objective\n",
      "    scores = cross_val_score(model,X_train, y_train, scoring='roc_auc', cv=cv)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/sklearn/model_selection/_validation.py\", line 562, in cross_val_score\n",
      "    cv_results = cross_validate(\n",
      "                 ^^^^^^^^^^^^^^^\n",
      "  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/sklearn/utils/_param_validation.py\", line 211, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/sklearn/model_selection/_validation.py\", line 328, in cross_validate\n",
      "    _warn_or_raise_about_fit_failures(results, error_score)\n",
      "  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/sklearn/model_selection/_validation.py\", line 414, in _warn_or_raise_about_fit_failures\n",
      "    raise ValueError(all_fits_failed_message)\n",
      "ValueError: \n",
      "All the 5 fits failed.\n",
      "It is very likely that your model is misconfigured.\n",
      "You can try to debug the error by setting error_score='raise'.\n",
      "\n",
      "Below are more details about the failures:\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/sklearn/model_selection/_validation.py\", line 729, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\n",
      "    return func(**kwargs)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/sklearn.py\", line 1531, in fit\n",
      "    self._Booster = train(\n",
      "                    ^^^^^^\n",
      "  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\n",
      "    return func(**kwargs)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/training.py\", line 181, in train\n",
      "    bst.update(dtrain, iteration=i, fobj=obj)\n",
      "  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 2100, in update\n",
      "    _check_call(\n",
      "  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 284, in _check_call\n",
      "    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\n",
      "xgboost.core.XGBoostError: [12:13:43] /workspace/src/tree/updater_gpu_hist.cu:861: Exception in gpu_hist: [12:13:43] /workspace/src/tree/updater_gpu_hist.cu:867: Check failed: ctx_->Ordinal() >= 0 (-1 vs. 0) : Must have at least one device\n",
      "Stack trace:\n",
      "  [bt] (0) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7fe3bee99cbc]\n",
      "  [bt] (1) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2c55d) [0x7fe3bf99855d]\n",
      "  [bt] (2) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2ca04) [0x7fe3bf998a04]\n",
      "  [bt] (3) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x57f526) [0x7fe3bf1eb526]\n",
      "  [bt] (4) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5808f4) [0x7fe3bf1ec8f4]\n",
      "  [bt] (5) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5cb1f8) [0x7fe3bf2371f8]\n",
      "  [bt] (6) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterUpdateOneIter+0x6f) [0x7fe3beda352f]\n",
      "  [bt] (7) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0xa052) [0x7fe4c8bf6052]\n",
      "  [bt] (8) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0x8925) [0x7fe4c8bf4925]\n",
      "\n",
      "\n",
      "\n",
      "Stack trace:\n",
      "  [bt] (0) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7fe3bee99cbc]\n",
      "  [bt] (1) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2cbd4) [0x7fe3bf998bd4]\n",
      "  [bt] (2) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x57f526) [0x7fe3bf1eb526]\n",
      "  [bt] (3) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5808f4) [0x7fe3bf1ec8f4]\n",
      "  [bt] (4) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5cb1f8) [0x7fe3bf2371f8]\n",
      "  [bt] (5) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterUpdateOneIter+0x6f) [0x7fe3beda352f]\n",
      "  [bt] (6) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0xa052) [0x7fe4c8bf6052]\n",
      "  [bt] (7) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0x8925) [0x7fe4c8bf4925]\n",
      "  [bt] (8) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xde) [0x7fe4c8bf506e]\n",
      "\n",
      "\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/sklearn/model_selection/_validation.py\", line 729, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\n",
      "    return func(**kwargs)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/sklearn.py\", line 1531, in fit\n",
      "    self._Booster = train(\n",
      "                    ^^^^^^\n",
      "  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\n",
      "    return func(**kwargs)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/training.py\", line 181, in train\n",
      "    bst.update(dtrain, iteration=i, fobj=obj)\n",
      "  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 2100, in update\n",
      "    _check_call(\n",
      "  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 284, in _check_call\n",
      "    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\n",
      "xgboost.core.XGBoostError: [12:13:50] /workspace/src/tree/updater_gpu_hist.cu:861: Exception in gpu_hist: [12:13:50] /workspace/src/tree/updater_gpu_hist.cu:867: Check failed: ctx_->Ordinal() >= 0 (-1 vs. 0) : Must have at least one device\n",
      "Stack trace:\n",
      "  [bt] (0) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7fe3bee99cbc]\n",
      "  [bt] (1) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2c55d) [0x7fe3bf99855d]\n",
      "  [bt] (2) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2ca04) [0x7fe3bf998a04]\n",
      "  [bt] (3) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x57f526) [0x7fe3bf1eb526]\n",
      "  [bt] (4) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5808f4) [0x7fe3bf1ec8f4]\n",
      "  [bt] (5) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5cb1f8) [0x7fe3bf2371f8]\n",
      "  [bt] (6) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterUpdateOneIter+0x6f) [0x7fe3beda352f]\n",
      "  [bt] (7) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0xa052) [0x7fe4c8bf6052]\n",
      "  [bt] (8) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0x8925) [0x7fe4c8bf4925]\n",
      "\n",
      "\n",
      "\n",
      "Stack trace:\n",
      "  [bt] (0) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7fe3bee99cbc]\n",
      "  [bt] (1) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2cbd4) [0x7fe3bf998bd4]\n",
      "  [bt] (2) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x57f526) [0x7fe3bf1eb526]\n",
      "  [bt] (3) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5808f4) [0x7fe3bf1ec8f4]\n",
      "  [bt] (4) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5cb1f8) [0x7fe3bf2371f8]\n",
      "  [bt] (5) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterUpdateOneIter+0x6f) [0x7fe3beda352f]\n",
      "  [bt] (6) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0xa052) [0x7fe4c8bf6052]\n",
      "  [bt] (7) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0x8925) [0x7fe4c8bf4925]\n",
      "  [bt] (8) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xde) [0x7fe4c8bf506e]\n",
      "\n",
      "\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/sklearn/model_selection/_validation.py\", line 729, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\n",
      "    return func(**kwargs)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/sklearn.py\", line 1531, in fit\n",
      "    self._Booster = train(\n",
      "                    ^^^^^^\n",
      "  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\n",
      "    return func(**kwargs)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/training.py\", line 181, in train\n",
      "    bst.update(dtrain, iteration=i, fobj=obj)\n",
      "  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 2100, in update\n",
      "    _check_call(\n",
      "  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 284, in _check_call\n",
      "    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\n",
      "xgboost.core.XGBoostError: [12:13:57] /workspace/src/tree/updater_gpu_hist.cu:861: Exception in gpu_hist: [12:13:57] /workspace/src/tree/updater_gpu_hist.cu:867: Check failed: ctx_->Ordinal() >= 0 (-1 vs. 0) : Must have at least one device\n",
      "Stack trace:\n",
      "  [bt] (0) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7fe3bee99cbc]\n",
      "  [bt] (1) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2c55d) [0x7fe3bf99855d]\n",
      "  [bt] (2) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2ca04) [0x7fe3bf998a04]\n",
      "  [bt] (3) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x57f526) [0x7fe3bf1eb526]\n",
      "  [bt] (4) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5808f4) [0x7fe3bf1ec8f4]\n",
      "  [bt] (5) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5cb1f8) [0x7fe3bf2371f8]\n",
      "  [bt] (6) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterUpdateOneIter+0x6f) [0x7fe3beda352f]\n",
      "  [bt] (7) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0xa052) [0x7fe4c8bf6052]\n",
      "  [bt] (8) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0x8925) [0x7fe4c8bf4925]\n",
      "\n",
      "\n",
      "\n",
      "Stack trace:\n",
      "  [bt] (0) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7fe3bee99cbc]\n",
      "  [bt] (1) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2cbd4) [0x7fe3bf998bd4]\n",
      "  [bt] (2) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x57f526) [0x7fe3bf1eb526]\n",
      "  [bt] (3) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5808f4) [0x7fe3bf1ec8f4]\n",
      "  [bt] (4) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5cb1f8) [0x7fe3bf2371f8]\n",
      "  [bt] (5) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterUpdateOneIter+0x6f) [0x7fe3beda352f]\n",
      "  [bt] (6) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0xa052) [0x7fe4c8bf6052]\n",
      "  [bt] (7) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0x8925) [0x7fe4c8bf4925]\n",
      "  [bt] (8) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xde) [0x7fe4c8bf506e]\n",
      "\n",
      "\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/sklearn/model_selection/_validation.py\", line 729, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\n",
      "    return func(**kwargs)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/sklearn.py\", line 1531, in fit\n",
      "    self._Booster = train(\n",
      "                    ^^^^^^\n",
      "  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\n",
      "    return func(**kwargs)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/training.py\", line 181, in train\n",
      "    bst.update(dtrain, iteration=i, fobj=obj)\n",
      "  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 2100, in update\n",
      "    _check_call(\n",
      "  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 284, in _check_call\n",
      "    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\n",
      "xgboost.core.XGBoostError: [12:14:04] /workspace/src/tree/updater_gpu_hist.cu:861: Exception in gpu_hist: [12:14:04] /workspace/src/tree/updater_gpu_hist.cu:867: Check failed: ctx_->Ordinal() >= 0 (-1 vs. 0) : Must have at least one device\n",
      "Stack trace:\n",
      "  [bt] (0) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7fe3bee99cbc]\n",
      "  [bt] (1) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2c55d) [0x7fe3bf99855d]\n",
      "  [bt] (2) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2ca04) [0x7fe3bf998a04]\n",
      "  [bt] (3) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x57f526) [0x7fe3bf1eb526]\n",
      "  [bt] (4) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5808f4) [0x7fe3bf1ec8f4]\n",
      "  [bt] (5) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5cb1f8) [0x7fe3bf2371f8]\n",
      "  [bt] (6) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterUpdateOneIter+0x6f) [0x7fe3beda352f]\n",
      "  [bt] (7) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0xa052) [0x7fe4c8bf6052]\n",
      "  [bt] (8) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0x8925) [0x7fe4c8bf4925]\n",
      "\n",
      "\n",
      "\n",
      "Stack trace:\n",
      "  [bt] (0) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7fe3bee99cbc]\n",
      "  [bt] (1) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2cbd4) [0x7fe3bf998bd4]\n",
      "  [bt] (2) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x57f526) [0x7fe3bf1eb526]\n",
      "  [bt] (3) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5808f4) [0x7fe3bf1ec8f4]\n",
      "  [bt] (4) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5cb1f8) [0x7fe3bf2371f8]\n",
      "  [bt] (5) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterUpdateOneIter+0x6f) [0x7fe3beda352f]\n",
      "  [bt] (6) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0xa052) [0x7fe4c8bf6052]\n",
      "  [bt] (7) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0x8925) [0x7fe4c8bf4925]\n",
      "  [bt] (8) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xde) [0x7fe4c8bf506e]\n",
      "\n",
      "\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/sklearn/model_selection/_validation.py\", line 729, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\n",
      "    return func(**kwargs)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/sklearn.py\", line 1531, in fit\n",
      "    self._Booster = train(\n",
      "                    ^^^^^^\n",
      "  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\n",
      "    return func(**kwargs)\n",
      "           ^^^^^^^^^^^^^^\n",
      "  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/training.py\", line 181, in train\n",
      "    bst.update(dtrain, iteration=i, fobj=obj)\n",
      "  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 2100, in update\n",
      "    _check_call(\n",
      "  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 284, in _check_call\n",
      "    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\n",
      "xgboost.core.XGBoostError: [12:14:11] /workspace/src/tree/updater_gpu_hist.cu:861: Exception in gpu_hist: [12:14:11] /workspace/src/tree/updater_gpu_hist.cu:867: Check failed: ctx_->Ordinal() >= 0 (-1 vs. 0) : Must have at least one device\n",
      "Stack trace:\n",
      "  [bt] (0) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7fe3bee99cbc]\n",
      "  [bt] (1) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2c55d) [0x7fe3bf99855d]\n",
      "  [bt] (2) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2ca04) [0x7fe3bf998a04]\n",
      "  [bt] (3) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x57f526) [0x7fe3bf1eb526]\n",
      "  [bt] (4) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5808f4) [0x7fe3bf1ec8f4]\n",
      "  [bt] (5) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5cb1f8) [0x7fe3bf2371f8]\n",
      "  [bt] (6) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterUpdateOneIter+0x6f) [0x7fe3beda352f]\n",
      "  [bt] (7) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0xa052) [0x7fe4c8bf6052]\n",
      "  [bt] (8) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0x8925) [0x7fe4c8bf4925]\n",
      "\n",
      "\n",
      "\n",
      "Stack trace:\n",
      "  [bt] (0) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7fe3bee99cbc]\n",
      "  [bt] (1) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2cbd4) [0x7fe3bf998bd4]\n",
      "  [bt] (2) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x57f526) [0x7fe3bf1eb526]\n",
      "  [bt] (3) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5808f4) [0x7fe3bf1ec8f4]\n",
      "  [bt] (4) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5cb1f8) [0x7fe3bf2371f8]\n",
      "  [bt] (5) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterUpdateOneIter+0x6f) [0x7fe3beda352f]\n",
      "  [bt] (6) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0xa052) [0x7fe4c8bf6052]\n",
      "  [bt] (7) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0x8925) [0x7fe4c8bf4925]\n",
      "  [bt] (8) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xde) [0x7fe4c8bf506e]\n",
      "\n",
      "\n",
      "\n",
      "[W 2025-02-24 12:14:11,066] Trial 0 failed with value None.\n"
     ]
    },
    {
     "ename": "ValueError",
     "evalue": "\nAll the 5 fits failed.\nIt is very likely that your model is misconfigured.\nYou can try to debug the error by setting error_score='raise'.\n\nBelow are more details about the failures:\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/sklearn/model_selection/_validation.py\", line 729, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/sklearn.py\", line 1531, in fit\n    self._Booster = train(\n                    ^^^^^^\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/training.py\", line 181, in train\n    bst.update(dtrain, iteration=i, fobj=obj)\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 2100, in update\n    _check_call(\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 284, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [12:13:43] /workspace/src/tree/updater_gpu_hist.cu:861: Exception in gpu_hist: [12:13:43] /workspace/src/tree/updater_gpu_hist.cu:867: Check failed: ctx_->Ordinal() >= 0 (-1 vs. 0) : Must have at least one device\nStack trace:\n  [bt] (0) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7fe3bee99cbc]\n  [bt] (1) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2c55d) [0x7fe3bf99855d]\n  [bt] (2) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2ca04) [0x7fe3bf998a04]\n  [bt] (3) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x57f526) [0x7fe3bf1eb526]\n  [bt] (4) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5808f4) [0x7fe3bf1ec8f4]\n  [bt] (5) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5cb1f8) [0x7fe3bf2371f8]\n  [bt] (6) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterUpdateOneIter+0x6f) [0x7fe3beda352f]\n  [bt] (7) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0xa052) [0x7fe4c8bf6052]\n  [bt] (8) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0x8925) [0x7fe4c8bf4925]\n\n\n\nStack trace:\n  [bt] (0) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7fe3bee99cbc]\n  [bt] (1) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2cbd4) [0x7fe3bf998bd4]\n  [bt] (2) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x57f526) [0x7fe3bf1eb526]\n  [bt] (3) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5808f4) [0x7fe3bf1ec8f4]\n  [bt] (4) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5cb1f8) [0x7fe3bf2371f8]\n  [bt] (5) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterUpdateOneIter+0x6f) [0x7fe3beda352f]\n  [bt] (6) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0xa052) [0x7fe4c8bf6052]\n  [bt] (7) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0x8925) [0x7fe4c8bf4925]\n  [bt] (8) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xde) [0x7fe4c8bf506e]\n\n\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/sklearn/model_selection/_validation.py\", line 729, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/sklearn.py\", line 1531, in fit\n    self._Booster = train(\n                    ^^^^^^\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/training.py\", line 181, in train\n    bst.update(dtrain, iteration=i, fobj=obj)\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 2100, in update\n    _check_call(\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 284, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [12:13:50] /workspace/src/tree/updater_gpu_hist.cu:861: Exception in gpu_hist: [12:13:50] /workspace/src/tree/updater_gpu_hist.cu:867: Check failed: ctx_->Ordinal() >= 0 (-1 vs. 0) : Must have at least one device\nStack trace:\n  [bt] (0) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7fe3bee99cbc]\n  [bt] (1) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2c55d) [0x7fe3bf99855d]\n  [bt] (2) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2ca04) [0x7fe3bf998a04]\n  [bt] (3) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x57f526) [0x7fe3bf1eb526]\n  [bt] (4) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5808f4) [0x7fe3bf1ec8f4]\n  [bt] (5) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5cb1f8) [0x7fe3bf2371f8]\n  [bt] (6) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterUpdateOneIter+0x6f) [0x7fe3beda352f]\n  [bt] (7) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0xa052) [0x7fe4c8bf6052]\n  [bt] (8) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0x8925) [0x7fe4c8bf4925]\n\n\n\nStack trace:\n  [bt] (0) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7fe3bee99cbc]\n  [bt] (1) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2cbd4) [0x7fe3bf998bd4]\n  [bt] (2) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x57f526) [0x7fe3bf1eb526]\n  [bt] (3) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5808f4) [0x7fe3bf1ec8f4]\n  [bt] (4) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5cb1f8) [0x7fe3bf2371f8]\n  [bt] (5) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterUpdateOneIter+0x6f) [0x7fe3beda352f]\n  [bt] (6) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0xa052) [0x7fe4c8bf6052]\n  [bt] (7) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0x8925) [0x7fe4c8bf4925]\n  [bt] (8) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xde) [0x7fe4c8bf506e]\n\n\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/sklearn/model_selection/_validation.py\", line 729, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/sklearn.py\", line 1531, in fit\n    self._Booster = train(\n                    ^^^^^^\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/training.py\", line 181, in train\n    bst.update(dtrain, iteration=i, fobj=obj)\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 2100, in update\n    _check_call(\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 284, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [12:13:57] /workspace/src/tree/updater_gpu_hist.cu:861: Exception in gpu_hist: [12:13:57] /workspace/src/tree/updater_gpu_hist.cu:867: Check failed: ctx_->Ordinal() >= 0 (-1 vs. 0) : Must have at least one device\nStack trace:\n  [bt] (0) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7fe3bee99cbc]\n  [bt] (1) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2c55d) [0x7fe3bf99855d]\n  [bt] (2) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2ca04) [0x7fe3bf998a04]\n  [bt] (3) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x57f526) [0x7fe3bf1eb526]\n  [bt] (4) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5808f4) [0x7fe3bf1ec8f4]\n  [bt] (5) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5cb1f8) [0x7fe3bf2371f8]\n  [bt] (6) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterUpdateOneIter+0x6f) [0x7fe3beda352f]\n  [bt] (7) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0xa052) [0x7fe4c8bf6052]\n  [bt] (8) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0x8925) [0x7fe4c8bf4925]\n\n\n\nStack trace:\n  [bt] (0) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7fe3bee99cbc]\n  [bt] (1) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2cbd4) [0x7fe3bf998bd4]\n  [bt] (2) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x57f526) [0x7fe3bf1eb526]\n  [bt] (3) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5808f4) [0x7fe3bf1ec8f4]\n  [bt] (4) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5cb1f8) [0x7fe3bf2371f8]\n  [bt] (5) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterUpdateOneIter+0x6f) [0x7fe3beda352f]\n  [bt] (6) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0xa052) [0x7fe4c8bf6052]\n  [bt] (7) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0x8925) [0x7fe4c8bf4925]\n  [bt] (8) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xde) [0x7fe4c8bf506e]\n\n\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/sklearn/model_selection/_validation.py\", line 729, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/sklearn.py\", line 1531, in fit\n    self._Booster = train(\n                    ^^^^^^\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/training.py\", line 181, in train\n    bst.update(dtrain, iteration=i, fobj=obj)\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 2100, in update\n    _check_call(\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 284, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [12:14:04] /workspace/src/tree/updater_gpu_hist.cu:861: Exception in gpu_hist: [12:14:04] /workspace/src/tree/updater_gpu_hist.cu:867: Check failed: ctx_->Ordinal() >= 0 (-1 vs. 0) : Must have at least one device\nStack trace:\n  [bt] (0) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7fe3bee99cbc]\n  [bt] (1) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2c55d) [0x7fe3bf99855d]\n  [bt] (2) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2ca04) [0x7fe3bf998a04]\n  [bt] (3) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x57f526) [0x7fe3bf1eb526]\n  [bt] (4) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5808f4) [0x7fe3bf1ec8f4]\n  [bt] (5) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5cb1f8) [0x7fe3bf2371f8]\n  [bt] (6) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterUpdateOneIter+0x6f) [0x7fe3beda352f]\n  [bt] (7) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0xa052) [0x7fe4c8bf6052]\n  [bt] (8) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0x8925) [0x7fe4c8bf4925]\n\n\n\nStack trace:\n  [bt] (0) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7fe3bee99cbc]\n  [bt] (1) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2cbd4) [0x7fe3bf998bd4]\n  [bt] (2) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x57f526) [0x7fe3bf1eb526]\n  [bt] (3) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5808f4) [0x7fe3bf1ec8f4]\n  [bt] (4) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5cb1f8) [0x7fe3bf2371f8]\n  [bt] (5) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterUpdateOneIter+0x6f) [0x7fe3beda352f]\n  [bt] (6) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0xa052) [0x7fe4c8bf6052]\n  [bt] (7) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0x8925) [0x7fe4c8bf4925]\n  [bt] (8) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xde) [0x7fe4c8bf506e]\n\n\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/sklearn/model_selection/_validation.py\", line 729, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/sklearn.py\", line 1531, in fit\n    self._Booster = train(\n                    ^^^^^^\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/training.py\", line 181, in train\n    bst.update(dtrain, iteration=i, fobj=obj)\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 2100, in update\n    _check_call(\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 284, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [12:14:11] /workspace/src/tree/updater_gpu_hist.cu:861: Exception in gpu_hist: [12:14:11] /workspace/src/tree/updater_gpu_hist.cu:867: Check failed: ctx_->Ordinal() >= 0 (-1 vs. 0) : Must have at least one device\nStack trace:\n  [bt] (0) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7fe3bee99cbc]\n  [bt] (1) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2c55d) [0x7fe3bf99855d]\n  [bt] (2) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2ca04) [0x7fe3bf998a04]\n  [bt] (3) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x57f526) [0x7fe3bf1eb526]\n  [bt] (4) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5808f4) [0x7fe3bf1ec8f4]\n  [bt] (5) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5cb1f8) [0x7fe3bf2371f8]\n  [bt] (6) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterUpdateOneIter+0x6f) [0x7fe3beda352f]\n  [bt] (7) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0xa052) [0x7fe4c8bf6052]\n  [bt] (8) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0x8925) [0x7fe4c8bf4925]\n\n\n\nStack trace:\n  [bt] (0) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7fe3bee99cbc]\n  [bt] (1) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2cbd4) [0x7fe3bf998bd4]\n  [bt] (2) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x57f526) [0x7fe3bf1eb526]\n  [bt] (3) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5808f4) [0x7fe3bf1ec8f4]\n  [bt] (4) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5cb1f8) [0x7fe3bf2371f8]\n  [bt] (5) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterUpdateOneIter+0x6f) [0x7fe3beda352f]\n  [bt] (6) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0xa052) [0x7fe4c8bf6052]\n  [bt] (7) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0x8925) [0x7fe4c8bf4925]\n  [bt] (8) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xde) [0x7fe4c8bf506e]\n\n\n",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[14], line 5\u001b[0m\n\u001b[1;32m      2\u001b[0m study \u001b[38;5;241m=\u001b[39m optuna\u001b[38;5;241m.\u001b[39mcreate_study(direction\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mmaximize\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n\u001b[1;32m      4\u001b[0m \u001b[38;5;66;03m#B√∫squeda\u001b[39;00m\n\u001b[0;32m----> 5\u001b[0m \u001b[43mstudy\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43moptimize\u001b[49m\u001b[43m(\u001b[49m\u001b[43mobjective\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mn_trials\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;241;43m50\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mshow_progress_bar\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43;01mTrue\u001b[39;49;00m\u001b[43m)\u001b[49m\n\u001b[1;32m      7\u001b[0m \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mBest trial:\u001b[39m\u001b[38;5;124m\"\u001b[39m, study\u001b[38;5;241m.\u001b[39mbest_trial\u001b[38;5;241m.\u001b[39mnumber)\n\u001b[1;32m      8\u001b[0m \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mBest value (mean AUC):\u001b[39m\u001b[38;5;124m\"\u001b[39m, study\u001b[38;5;241m.\u001b[39mbest_value)\n",
      "File \u001b[0;32m~/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/optuna/study/study.py:475\u001b[0m, in \u001b[0;36mStudy.optimize\u001b[0;34m(self, func, n_trials, timeout, n_jobs, catch, callbacks, gc_after_trial, show_progress_bar)\u001b[0m\n\u001b[1;32m    373\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21moptimize\u001b[39m(\n\u001b[1;32m    374\u001b[0m     \u001b[38;5;28mself\u001b[39m,\n\u001b[1;32m    375\u001b[0m     func: ObjectiveFuncType,\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    382\u001b[0m     show_progress_bar: \u001b[38;5;28mbool\u001b[39m \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mFalse\u001b[39;00m,\n\u001b[1;32m    383\u001b[0m ) \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[1;32m    384\u001b[0m \u001b[38;5;250m    \u001b[39m\u001b[38;5;124;03m\"\"\"Optimize an objective function.\u001b[39;00m\n\u001b[1;32m    385\u001b[0m \n\u001b[1;32m    386\u001b[0m \u001b[38;5;124;03m    Optimization is done by choosing a suitable set of hyperparameter values from a given\u001b[39;00m\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    473\u001b[0m \u001b[38;5;124;03m            If nested invocation of this method occurs.\u001b[39;00m\n\u001b[1;32m    474\u001b[0m \u001b[38;5;124;03m    \"\"\"\u001b[39;00m\n\u001b[0;32m--> 475\u001b[0m     \u001b[43m_optimize\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m    476\u001b[0m \u001b[43m        \u001b[49m\u001b[43mstudy\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m,\u001b[49m\n\u001b[1;32m    477\u001b[0m \u001b[43m        \u001b[49m\u001b[43mfunc\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mfunc\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    478\u001b[0m \u001b[43m        \u001b[49m\u001b[43mn_trials\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mn_trials\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    479\u001b[0m \u001b[43m        \u001b[49m\u001b[43mtimeout\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mtimeout\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    480\u001b[0m \u001b[43m        \u001b[49m\u001b[43mn_jobs\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mn_jobs\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    481\u001b[0m \u001b[43m        \u001b[49m\u001b[43mcatch\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43mtuple\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43mcatch\u001b[49m\u001b[43m)\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43;01mif\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[38;5;28;43misinstance\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43mcatch\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mIterable\u001b[49m\u001b[43m)\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43;01melse\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[43m(\u001b[49m\u001b[43mcatch\u001b[49m\u001b[43m,\u001b[49m\u001b[43m)\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    482\u001b[0m \u001b[43m        \u001b[49m\u001b[43mcallbacks\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mcallbacks\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    483\u001b[0m \u001b[43m        \u001b[49m\u001b[43mgc_after_trial\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mgc_after_trial\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    484\u001b[0m \u001b[43m        \u001b[49m\u001b[43mshow_progress_bar\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mshow_progress_bar\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    485\u001b[0m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/optuna/study/_optimize.py:63\u001b[0m, in \u001b[0;36m_optimize\u001b[0;34m(study, func, n_trials, timeout, n_jobs, catch, callbacks, gc_after_trial, show_progress_bar)\u001b[0m\n\u001b[1;32m     61\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m     62\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m n_jobs \u001b[38;5;241m==\u001b[39m \u001b[38;5;241m1\u001b[39m:\n\u001b[0;32m---> 63\u001b[0m         \u001b[43m_optimize_sequential\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m     64\u001b[0m \u001b[43m            \u001b[49m\u001b[43mstudy\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m     65\u001b[0m \u001b[43m            \u001b[49m\u001b[43mfunc\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m     66\u001b[0m \u001b[43m            \u001b[49m\u001b[43mn_trials\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m     67\u001b[0m \u001b[43m            \u001b[49m\u001b[43mtimeout\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m     68\u001b[0m \u001b[43m            \u001b[49m\u001b[43mcatch\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m     69\u001b[0m \u001b[43m            \u001b[49m\u001b[43mcallbacks\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m     70\u001b[0m \u001b[43m            \u001b[49m\u001b[43mgc_after_trial\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m     71\u001b[0m \u001b[43m            \u001b[49m\u001b[43mreseed_sampler_rng\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43;01mFalse\u001b[39;49;00m\u001b[43m,\u001b[49m\n\u001b[1;32m     72\u001b[0m \u001b[43m            \u001b[49m\u001b[43mtime_start\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43;01mNone\u001b[39;49;00m\u001b[43m,\u001b[49m\n\u001b[1;32m     73\u001b[0m \u001b[43m            \u001b[49m\u001b[43mprogress_bar\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mprogress_bar\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m     74\u001b[0m \u001b[43m        \u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m     75\u001b[0m     \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m     76\u001b[0m         \u001b[38;5;28;01mif\u001b[39;00m n_jobs \u001b[38;5;241m==\u001b[39m \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m1\u001b[39m:\n",
      "File \u001b[0;32m~/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/optuna/study/_optimize.py:160\u001b[0m, in \u001b[0;36m_optimize_sequential\u001b[0;34m(study, func, n_trials, timeout, catch, callbacks, gc_after_trial, reseed_sampler_rng, time_start, progress_bar)\u001b[0m\n\u001b[1;32m    157\u001b[0m         \u001b[38;5;28;01mbreak\u001b[39;00m\n\u001b[1;32m    159\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m--> 160\u001b[0m     frozen_trial \u001b[38;5;241m=\u001b[39m \u001b[43m_run_trial\u001b[49m\u001b[43m(\u001b[49m\u001b[43mstudy\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mfunc\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mcatch\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    161\u001b[0m \u001b[38;5;28;01mfinally\u001b[39;00m:\n\u001b[1;32m    162\u001b[0m     \u001b[38;5;66;03m# The following line mitigates memory problems that can be occurred in some\u001b[39;00m\n\u001b[1;32m    163\u001b[0m     \u001b[38;5;66;03m# environments (e.g., services that use computing containers such as GitHub Actions).\u001b[39;00m\n\u001b[1;32m    164\u001b[0m     \u001b[38;5;66;03m# Please refer to the following PR for further details:\u001b[39;00m\n\u001b[1;32m    165\u001b[0m     \u001b[38;5;66;03m# https://github.com/optuna/optuna/pull/325.\u001b[39;00m\n\u001b[1;32m    166\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m gc_after_trial:\n",
      "File \u001b[0;32m~/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/optuna/study/_optimize.py:248\u001b[0m, in \u001b[0;36m_run_trial\u001b[0;34m(study, func, catch)\u001b[0m\n\u001b[1;32m    241\u001b[0m         \u001b[38;5;28;01massert\u001b[39;00m \u001b[38;5;28;01mFalse\u001b[39;00m, \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mShould not reach.\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m    243\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m (\n\u001b[1;32m    244\u001b[0m     frozen_trial\u001b[38;5;241m.\u001b[39mstate \u001b[38;5;241m==\u001b[39m TrialState\u001b[38;5;241m.\u001b[39mFAIL\n\u001b[1;32m    245\u001b[0m     \u001b[38;5;129;01mand\u001b[39;00m func_err \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[1;32m    246\u001b[0m     \u001b[38;5;129;01mand\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28misinstance\u001b[39m(func_err, catch)\n\u001b[1;32m    247\u001b[0m ):\n\u001b[0;32m--> 248\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m func_err\n\u001b[1;32m    249\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m frozen_trial\n",
      "File \u001b[0;32m~/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/optuna/study/_optimize.py:197\u001b[0m, in \u001b[0;36m_run_trial\u001b[0;34m(study, func, catch)\u001b[0m\n\u001b[1;32m    195\u001b[0m \u001b[38;5;28;01mwith\u001b[39;00m get_heartbeat_thread(trial\u001b[38;5;241m.\u001b[39m_trial_id, study\u001b[38;5;241m.\u001b[39m_storage):\n\u001b[1;32m    196\u001b[0m     \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m--> 197\u001b[0m         value_or_values \u001b[38;5;241m=\u001b[39m \u001b[43mfunc\u001b[49m\u001b[43m(\u001b[49m\u001b[43mtrial\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    198\u001b[0m     \u001b[38;5;28;01mexcept\u001b[39;00m exceptions\u001b[38;5;241m.\u001b[39mTrialPruned \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[1;32m    199\u001b[0m         \u001b[38;5;66;03m# TODO(mamu): Handle multi-objective cases.\u001b[39;00m\n\u001b[1;32m    200\u001b[0m         state \u001b[38;5;241m=\u001b[39m TrialState\u001b[38;5;241m.\u001b[39mPRUNED\n",
      "Cell \u001b[0;32mIn[13], line 26\u001b[0m, in \u001b[0;36mobjective\u001b[0;34m(trial)\u001b[0m\n\u001b[1;32m     17\u001b[0m model \u001b[38;5;241m=\u001b[39m XGBClassifier(\n\u001b[1;32m     18\u001b[0m     \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mparams,\n\u001b[1;32m     19\u001b[0m     objective\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mbinary:logistic\u001b[39m\u001b[38;5;124m\"\u001b[39m,\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m     22\u001b[0m     random_state\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m42\u001b[39m\n\u001b[1;32m     23\u001b[0m )\n\u001b[1;32m     25\u001b[0m cv\u001b[38;5;241m=\u001b[39mStratifiedKFold(n_splits\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m5\u001b[39m, shuffle\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mTrue\u001b[39;00m, random_state\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m42\u001b[39m)\n\u001b[0;32m---> 26\u001b[0m scores \u001b[38;5;241m=\u001b[39m \u001b[43mcross_val_score\u001b[49m\u001b[43m(\u001b[49m\u001b[43mmodel\u001b[49m\u001b[43m,\u001b[49m\u001b[43mX_train\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43my_train\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mscoring\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43mroc_auc\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mcv\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mcv\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m     28\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m scores\u001b[38;5;241m.\u001b[39mmean()\n",
      "File \u001b[0;32m~/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/sklearn/model_selection/_validation.py:562\u001b[0m, in \u001b[0;36mcross_val_score\u001b[0;34m(estimator, X, y, groups, scoring, cv, n_jobs, verbose, fit_params, pre_dispatch, error_score)\u001b[0m\n\u001b[1;32m    559\u001b[0m \u001b[38;5;66;03m# To ensure multimetric format is not supported\u001b[39;00m\n\u001b[1;32m    560\u001b[0m scorer \u001b[38;5;241m=\u001b[39m check_scoring(estimator, scoring\u001b[38;5;241m=\u001b[39mscoring)\n\u001b[0;32m--> 562\u001b[0m cv_results \u001b[38;5;241m=\u001b[39m \u001b[43mcross_validate\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m    563\u001b[0m \u001b[43m    \u001b[49m\u001b[43mestimator\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mestimator\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    564\u001b[0m \u001b[43m    \u001b[49m\u001b[43mX\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mX\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    565\u001b[0m \u001b[43m    \u001b[49m\u001b[43my\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43my\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    566\u001b[0m \u001b[43m    \u001b[49m\u001b[43mgroups\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mgroups\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    567\u001b[0m \u001b[43m    \u001b[49m\u001b[43mscoring\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43m{\u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mscore\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m:\u001b[49m\u001b[43m \u001b[49m\u001b[43mscorer\u001b[49m\u001b[43m}\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    568\u001b[0m \u001b[43m    \u001b[49m\u001b[43mcv\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mcv\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    569\u001b[0m \u001b[43m    \u001b[49m\u001b[43mn_jobs\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mn_jobs\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    570\u001b[0m \u001b[43m    \u001b[49m\u001b[43mverbose\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mverbose\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    571\u001b[0m \u001b[43m    \u001b[49m\u001b[43mfit_params\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mfit_params\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    572\u001b[0m \u001b[43m    \u001b[49m\u001b[43mpre_dispatch\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mpre_dispatch\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    573\u001b[0m \u001b[43m    \u001b[49m\u001b[43merror_score\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43merror_score\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    574\u001b[0m \u001b[43m\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    575\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m cv_results[\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mtest_score\u001b[39m\u001b[38;5;124m\"\u001b[39m]\n",
      "File \u001b[0;32m~/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/sklearn/utils/_param_validation.py:211\u001b[0m, in \u001b[0;36mvalidate_params.<locals>.decorator.<locals>.wrapper\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m    205\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m    206\u001b[0m     \u001b[38;5;28;01mwith\u001b[39;00m config_context(\n\u001b[1;32m    207\u001b[0m         skip_parameter_validation\u001b[38;5;241m=\u001b[39m(\n\u001b[1;32m    208\u001b[0m             prefer_skip_nested_validation \u001b[38;5;129;01mor\u001b[39;00m global_skip_validation\n\u001b[1;32m    209\u001b[0m         )\n\u001b[1;32m    210\u001b[0m     ):\n\u001b[0;32m--> 211\u001b[0m         \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mfunc\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43margs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    212\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m InvalidParameterError \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[1;32m    213\u001b[0m     \u001b[38;5;66;03m# When the function is just a wrapper around an estimator, we allow\u001b[39;00m\n\u001b[1;32m    214\u001b[0m     \u001b[38;5;66;03m# the function to delegate validation to the estimator, but we replace\u001b[39;00m\n\u001b[1;32m    215\u001b[0m     \u001b[38;5;66;03m# the name of the estimator by the name of the function in the error\u001b[39;00m\n\u001b[1;32m    216\u001b[0m     \u001b[38;5;66;03m# message to avoid confusion.\u001b[39;00m\n\u001b[1;32m    217\u001b[0m     msg \u001b[38;5;241m=\u001b[39m re\u001b[38;5;241m.\u001b[39msub(\n\u001b[1;32m    218\u001b[0m         \u001b[38;5;124mr\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mparameter of \u001b[39m\u001b[38;5;124m\\\u001b[39m\u001b[38;5;124mw+ must be\u001b[39m\u001b[38;5;124m\"\u001b[39m,\n\u001b[1;32m    219\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mparameter of \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mfunc\u001b[38;5;241m.\u001b[39m\u001b[38;5;18m__qualname__\u001b[39m\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m must be\u001b[39m\u001b[38;5;124m\"\u001b[39m,\n\u001b[1;32m    220\u001b[0m         \u001b[38;5;28mstr\u001b[39m(e),\n\u001b[1;32m    221\u001b[0m     )\n",
      "File \u001b[0;32m~/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/sklearn/model_selection/_validation.py:328\u001b[0m, in \u001b[0;36mcross_validate\u001b[0;34m(estimator, X, y, groups, scoring, cv, n_jobs, verbose, fit_params, pre_dispatch, return_train_score, return_estimator, return_indices, error_score)\u001b[0m\n\u001b[1;32m    308\u001b[0m parallel \u001b[38;5;241m=\u001b[39m Parallel(n_jobs\u001b[38;5;241m=\u001b[39mn_jobs, verbose\u001b[38;5;241m=\u001b[39mverbose, pre_dispatch\u001b[38;5;241m=\u001b[39mpre_dispatch)\n\u001b[1;32m    309\u001b[0m results \u001b[38;5;241m=\u001b[39m parallel(\n\u001b[1;32m    310\u001b[0m     delayed(_fit_and_score)(\n\u001b[1;32m    311\u001b[0m         clone(estimator),\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    325\u001b[0m     \u001b[38;5;28;01mfor\u001b[39;00m train, test \u001b[38;5;129;01min\u001b[39;00m indices\n\u001b[1;32m    326\u001b[0m )\n\u001b[0;32m--> 328\u001b[0m \u001b[43m_warn_or_raise_about_fit_failures\u001b[49m\u001b[43m(\u001b[49m\u001b[43mresults\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43merror_score\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    330\u001b[0m \u001b[38;5;66;03m# For callable scoring, the return type is only know after calling. If the\u001b[39;00m\n\u001b[1;32m    331\u001b[0m \u001b[38;5;66;03m# return type is a dictionary, the error scores can now be inserted with\u001b[39;00m\n\u001b[1;32m    332\u001b[0m \u001b[38;5;66;03m# the correct key.\u001b[39;00m\n\u001b[1;32m    333\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mcallable\u001b[39m(scoring):\n",
      "File \u001b[0;32m~/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/sklearn/model_selection/_validation.py:414\u001b[0m, in \u001b[0;36m_warn_or_raise_about_fit_failures\u001b[0;34m(results, error_score)\u001b[0m\n\u001b[1;32m    407\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m num_failed_fits \u001b[38;5;241m==\u001b[39m num_fits:\n\u001b[1;32m    408\u001b[0m     all_fits_failed_message \u001b[38;5;241m=\u001b[39m (\n\u001b[1;32m    409\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124mAll the \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mnum_fits\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m fits failed.\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m    410\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mIt is very likely that your model is misconfigured.\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m    411\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mYou can try to debug the error by setting error_score=\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mraise\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124m.\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m    412\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mBelow are more details about the failures:\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;132;01m{\u001b[39;00mfit_errors_summary\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m    413\u001b[0m     )\n\u001b[0;32m--> 414\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mValueError\u001b[39;00m(all_fits_failed_message)\n\u001b[1;32m    416\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m    417\u001b[0m     some_fits_failed_message \u001b[38;5;241m=\u001b[39m (\n\u001b[1;32m    418\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;132;01m{\u001b[39;00mnum_failed_fits\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m fits failed out of a total of \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mnum_fits\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m.\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m    419\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mThe score on these train-test partitions for these parameters\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    423\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mBelow are more details about the failures:\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;132;01m{\u001b[39;00mfit_errors_summary\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m    424\u001b[0m     )\n",
      "\u001b[0;31mValueError\u001b[0m: \nAll the 5 fits failed.\nIt is very likely that your model is misconfigured.\nYou can try to debug the error by setting error_score='raise'.\n\nBelow are more details about the failures:\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/sklearn/model_selection/_validation.py\", line 729, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/sklearn.py\", line 1531, in fit\n    self._Booster = train(\n                    ^^^^^^\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/training.py\", line 181, in train\n    bst.update(dtrain, iteration=i, fobj=obj)\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 2100, in update\n    _check_call(\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 284, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [12:13:43] /workspace/src/tree/updater_gpu_hist.cu:861: Exception in gpu_hist: [12:13:43] /workspace/src/tree/updater_gpu_hist.cu:867: Check failed: ctx_->Ordinal() >= 0 (-1 vs. 0) : Must have at least one device\nStack trace:\n  [bt] (0) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7fe3bee99cbc]\n  [bt] (1) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2c55d) [0x7fe3bf99855d]\n  [bt] (2) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2ca04) [0x7fe3bf998a04]\n  [bt] (3) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x57f526) [0x7fe3bf1eb526]\n  [bt] (4) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5808f4) [0x7fe3bf1ec8f4]\n  [bt] (5) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5cb1f8) [0x7fe3bf2371f8]\n  [bt] (6) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterUpdateOneIter+0x6f) [0x7fe3beda352f]\n  [bt] (7) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0xa052) [0x7fe4c8bf6052]\n  [bt] (8) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0x8925) [0x7fe4c8bf4925]\n\n\n\nStack trace:\n  [bt] (0) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7fe3bee99cbc]\n  [bt] (1) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2cbd4) [0x7fe3bf998bd4]\n  [bt] (2) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x57f526) [0x7fe3bf1eb526]\n  [bt] (3) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5808f4) [0x7fe3bf1ec8f4]\n  [bt] (4) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5cb1f8) [0x7fe3bf2371f8]\n  [bt] (5) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterUpdateOneIter+0x6f) [0x7fe3beda352f]\n  [bt] (6) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0xa052) [0x7fe4c8bf6052]\n  [bt] (7) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0x8925) [0x7fe4c8bf4925]\n  [bt] (8) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xde) [0x7fe4c8bf506e]\n\n\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/sklearn/model_selection/_validation.py\", line 729, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/sklearn.py\", line 1531, in fit\n    self._Booster = train(\n                    ^^^^^^\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/training.py\", line 181, in train\n    bst.update(dtrain, iteration=i, fobj=obj)\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 2100, in update\n    _check_call(\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 284, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [12:13:50] /workspace/src/tree/updater_gpu_hist.cu:861: Exception in gpu_hist: [12:13:50] /workspace/src/tree/updater_gpu_hist.cu:867: Check failed: ctx_->Ordinal() >= 0 (-1 vs. 0) : Must have at least one device\nStack trace:\n  [bt] (0) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7fe3bee99cbc]\n  [bt] (1) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2c55d) [0x7fe3bf99855d]\n  [bt] (2) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2ca04) [0x7fe3bf998a04]\n  [bt] (3) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x57f526) [0x7fe3bf1eb526]\n  [bt] (4) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5808f4) [0x7fe3bf1ec8f4]\n  [bt] (5) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5cb1f8) [0x7fe3bf2371f8]\n  [bt] (6) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterUpdateOneIter+0x6f) [0x7fe3beda352f]\n  [bt] (7) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0xa052) [0x7fe4c8bf6052]\n  [bt] (8) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0x8925) [0x7fe4c8bf4925]\n\n\n\nStack trace:\n  [bt] (0) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7fe3bee99cbc]\n  [bt] (1) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2cbd4) [0x7fe3bf998bd4]\n  [bt] (2) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x57f526) [0x7fe3bf1eb526]\n  [bt] (3) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5808f4) [0x7fe3bf1ec8f4]\n  [bt] (4) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5cb1f8) [0x7fe3bf2371f8]\n  [bt] (5) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterUpdateOneIter+0x6f) [0x7fe3beda352f]\n  [bt] (6) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0xa052) [0x7fe4c8bf6052]\n  [bt] (7) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0x8925) [0x7fe4c8bf4925]\n  [bt] (8) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xde) [0x7fe4c8bf506e]\n\n\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/sklearn/model_selection/_validation.py\", line 729, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/sklearn.py\", line 1531, in fit\n    self._Booster = train(\n                    ^^^^^^\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/training.py\", line 181, in train\n    bst.update(dtrain, iteration=i, fobj=obj)\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 2100, in update\n    _check_call(\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 284, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [12:13:57] /workspace/src/tree/updater_gpu_hist.cu:861: Exception in gpu_hist: [12:13:57] /workspace/src/tree/updater_gpu_hist.cu:867: Check failed: ctx_->Ordinal() >= 0 (-1 vs. 0) : Must have at least one device\nStack trace:\n  [bt] (0) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7fe3bee99cbc]\n  [bt] (1) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2c55d) [0x7fe3bf99855d]\n  [bt] (2) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2ca04) [0x7fe3bf998a04]\n  [bt] (3) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x57f526) [0x7fe3bf1eb526]\n  [bt] (4) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5808f4) [0x7fe3bf1ec8f4]\n  [bt] (5) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5cb1f8) [0x7fe3bf2371f8]\n  [bt] (6) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterUpdateOneIter+0x6f) [0x7fe3beda352f]\n  [bt] (7) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0xa052) [0x7fe4c8bf6052]\n  [bt] (8) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0x8925) [0x7fe4c8bf4925]\n\n\n\nStack trace:\n  [bt] (0) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7fe3bee99cbc]\n  [bt] (1) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2cbd4) [0x7fe3bf998bd4]\n  [bt] (2) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x57f526) [0x7fe3bf1eb526]\n  [bt] (3) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5808f4) [0x7fe3bf1ec8f4]\n  [bt] (4) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5cb1f8) [0x7fe3bf2371f8]\n  [bt] (5) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterUpdateOneIter+0x6f) [0x7fe3beda352f]\n  [bt] (6) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0xa052) [0x7fe4c8bf6052]\n  [bt] (7) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0x8925) [0x7fe4c8bf4925]\n  [bt] (8) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xde) [0x7fe4c8bf506e]\n\n\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/sklearn/model_selection/_validation.py\", line 729, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/sklearn.py\", line 1531, in fit\n    self._Booster = train(\n                    ^^^^^^\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/training.py\", line 181, in train\n    bst.update(dtrain, iteration=i, fobj=obj)\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 2100, in update\n    _check_call(\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 284, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [12:14:04] /workspace/src/tree/updater_gpu_hist.cu:861: Exception in gpu_hist: [12:14:04] /workspace/src/tree/updater_gpu_hist.cu:867: Check failed: ctx_->Ordinal() >= 0 (-1 vs. 0) : Must have at least one device\nStack trace:\n  [bt] (0) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7fe3bee99cbc]\n  [bt] (1) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2c55d) [0x7fe3bf99855d]\n  [bt] (2) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2ca04) [0x7fe3bf998a04]\n  [bt] (3) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x57f526) [0x7fe3bf1eb526]\n  [bt] (4) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5808f4) [0x7fe3bf1ec8f4]\n  [bt] (5) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5cb1f8) [0x7fe3bf2371f8]\n  [bt] (6) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterUpdateOneIter+0x6f) [0x7fe3beda352f]\n  [bt] (7) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0xa052) [0x7fe4c8bf6052]\n  [bt] (8) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0x8925) [0x7fe4c8bf4925]\n\n\n\nStack trace:\n  [bt] (0) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7fe3bee99cbc]\n  [bt] (1) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2cbd4) [0x7fe3bf998bd4]\n  [bt] (2) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x57f526) [0x7fe3bf1eb526]\n  [bt] (3) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5808f4) [0x7fe3bf1ec8f4]\n  [bt] (4) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5cb1f8) [0x7fe3bf2371f8]\n  [bt] (5) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterUpdateOneIter+0x6f) [0x7fe3beda352f]\n  [bt] (6) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0xa052) [0x7fe4c8bf6052]\n  [bt] (7) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0x8925) [0x7fe4c8bf4925]\n  [bt] (8) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xde) [0x7fe4c8bf506e]\n\n\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/sklearn/model_selection/_validation.py\", line 729, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/sklearn.py\", line 1531, in fit\n    self._Booster = train(\n                    ^^^^^^\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 726, in inner_f\n    return func(**kwargs)\n           ^^^^^^^^^^^^^^\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/training.py\", line 181, in train\n    bst.update(dtrain, iteration=i, fobj=obj)\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 2100, in update\n    _check_call(\n  File \"/home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/core.py\", line 284, in _check_call\n    raise XGBoostError(py_str(_LIB.XGBGetLastError()))\nxgboost.core.XGBoostError: [12:14:11] /workspace/src/tree/updater_gpu_hist.cu:861: Exception in gpu_hist: [12:14:11] /workspace/src/tree/updater_gpu_hist.cu:867: Check failed: ctx_->Ordinal() >= 0 (-1 vs. 0) : Must have at least one device\nStack trace:\n  [bt] (0) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7fe3bee99cbc]\n  [bt] (1) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2c55d) [0x7fe3bf99855d]\n  [bt] (2) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2ca04) [0x7fe3bf998a04]\n  [bt] (3) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x57f526) [0x7fe3bf1eb526]\n  [bt] (4) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5808f4) [0x7fe3bf1ec8f4]\n  [bt] (5) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5cb1f8) [0x7fe3bf2371f8]\n  [bt] (6) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterUpdateOneIter+0x6f) [0x7fe3beda352f]\n  [bt] (7) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0xa052) [0x7fe4c8bf6052]\n  [bt] (8) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0x8925) [0x7fe4c8bf4925]\n\n\n\nStack trace:\n  [bt] (0) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x22dcbc) [0x7fe3bee99cbc]\n  [bt] (1) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xd2cbd4) [0x7fe3bf998bd4]\n  [bt] (2) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x57f526) [0x7fe3bf1eb526]\n  [bt] (3) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5808f4) [0x7fe3bf1ec8f4]\n  [bt] (4) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x5cb1f8) [0x7fe3bf2371f8]\n  [bt] (5) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(XGBoosterUpdateOneIter+0x6f) [0x7fe3beda352f]\n  [bt] (6) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0xa052) [0x7fe4c8bf6052]\n  [bt] (7) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(+0x8925) [0x7fe4c8bf4925]\n  [bt] (8) /home/yeray/miniconda3/envs/tfg-py3.12/lib/python3.12/lib-dynload/../../libffi.so.8(ffi_call+0xde) [0x7fe4c8bf506e]\n\n\n"
     ]
    }
   ],
   "source": [
    "#Estudio para maximizar\n",
    "study = optuna.create_study(direction=\"maximize\")\n",
    "\n",
    "#B√∫squeda\n",
    "study.optimize(objective, n_trials=50, show_progress_bar=True)\n",
    "\n",
    "print(\"Best trial:\", study.best_trial.number)\n",
    "print(\"Best value (mean AUC):\", study.best_value)\n",
    "print(\"Best hyperparams:\", study.best_params)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "af115205-c7c8-44e7-8904-65e4e0afdc48",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pickle\n",
    "with open(\"XGBoost_Optuna_Study_v1_space_reducido_mas_hiperpara.pkl\", \"wb\") as f:\n",
    "    pickle.dump(study, f)\n",
    "with open(\"XGBoost_Optuna_Study_v1_space_reducido_mas_hiperpara.pkl\", \"rb\") as f:\n",
    "    loaded_study = pickle.load(f)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "37e3232c-a287-4aea-a9fc-daaeb366da08",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "+----+----------+----------+----------------------------+----------------------------+------------------------+---------------------------+----------------+------------------------+--------------------+---------------------------+-----------------------+--------------------+---------------------+---------------------------+--------------------+----------+\n",
      "|    |   number |    value | datetime_start             | datetime_complete          | duration               |   params_colsample_bytree |   params_gamma |   params_learning_rate |   params_max_depth |   params_min_child_weight |   params_n_estimators |   params_reg_alpha |   params_reg_lambda |   params_scale_pos_weight |   params_subsample | state    |\n",
      "|----+----------+----------+----------------------------+----------------------------+------------------------+---------------------------+----------------+------------------------+--------------------+---------------------------+-----------------------+--------------------+---------------------+---------------------------+--------------------+----------|\n",
      "| 35 |       35 | 0.766467 | 2025-02-23 19:05:51.648664 | 2025-02-23 19:23:42.992309 | 0 days 00:17:51.343645 |                  0.609149 |        2.79174 |             0.016566   |                  7 |                        14 |                   950 |        2.98383e-07 |         0.000771683 |                   1.7469  |           0.753771 | COMPLETE |\n",
      "| 34 |       34 | 0.766461 | 2025-02-23 18:49:35.364806 | 2025-02-23 19:05:51.645108 | 0 days 00:16:16.280302 |                  0.620061 |        2.56817 |             0.0154127  |                  6 |                        14 |                  1000 |        2.52031e-07 |         0.00110387  |                   1.89547 |           0.757727 | COMPLETE |\n",
      "| 46 |       46 | 0.766399 | 2025-02-23 22:05:15.236729 | 2025-02-23 22:20:50.621878 | 0 days 00:15:35.385149 |                  0.535523 |        1.57097 |             0.0187693  |                  6 |                        15 |                  1000 |        7.2384e-06  |         4.86928e-05 |                   2.39789 |           0.676317 | COMPLETE |\n",
      "| 31 |       31 | 0.766357 | 2025-02-23 17:57:15.815215 | 2025-02-23 18:15:16.048308 | 0 days 00:18:00.233093 |                  0.613809 |        2.34799 |             0.0175067  |                  6 |                        23 |                   950 |        4.56709e-08 |         0.000110241 |                   1.01276 |           0.923685 | COMPLETE |\n",
      "| 41 |       41 | 0.766084 | 2025-02-23 20:47:50.655151 | 2025-02-23 21:03:23.247368 | 0 days 00:15:32.592217 |                  0.610996 |        2.53687 |             0.0166281  |                  6 |                        12 |                   950 |        1.99032e-07 |         8.69216e-05 |                   1.9704  |           0.870896 | COMPLETE |\n",
      "| 33 |       33 | 0.766062 | 2025-02-23 18:30:49.876401 | 2025-02-23 18:49:35.361852 | 0 days 00:18:45.485451 |                  0.63315  |        2.43031 |             0.0167189  |                  7 |                        14 |                  1000 |        3.63537e-07 |         0.00121678  |                   2.18691 |           0.826969 | COMPLETE |\n",
      "| 32 |       32 | 0.766053 | 2025-02-23 18:15:16.053597 | 2025-02-23 18:30:49.872830 | 0 days 00:15:33.819233 |                  0.616399 |        2.28153 |             0.0158812  |                  6 |                        23 |                   950 |        2.04723e-07 |         0.000133362 |                   1.99248 |           0.884517 | COMPLETE |\n",
      "| 39 |       39 | 0.765981 | 2025-02-23 20:13:43.138926 | 2025-02-23 20:30:04.129644 | 0 days 00:16:20.990718 |                  0.676327 |        3.20439 |             0.0144176  |                  6 |                        10 |                  1000 |        1.76326e-05 |         1.0625e-05  |                   2.47703 |           0.758076 | COMPLETE |\n",
      "| 42 |       42 | 0.765772 | 2025-02-23 21:03:23.251519 | 2025-02-23 21:21:15.739755 | 0 days 00:17:52.488236 |                  0.599034 |        2.6485  |             0.0158121  |                  7 |                        13 |                   950 |        8.67338e-08 |         0.0104662   |                   1.8577  |           0.765098 | COMPLETE |\n",
      "| 36 |       36 | 0.76537  | 2025-02-23 19:23:42.996857 | 2025-02-23 19:41:39.466679 | 0 days 00:17:56.469822 |                  0.693117 |        2.77901 |             0.00972739 |                  7 |                        14 |                   950 |        8.04801e-06 |         0.00133211  |                   1.59188 |           0.747286 | COMPLETE |\n",
      "+----+----------+----------+----------------------------+----------------------------+------------------------+---------------------------+----------------+------------------------+--------------------+---------------------------+-----------------------+--------------------+---------------------+---------------------------+--------------------+----------+\n"
     ]
    }
   ],
   "source": [
    "from tabulate import tabulate\n",
    "\n",
    "trials_df = loaded_study.trials_dataframe()\n",
    "\n",
    "df_sorted = trials_df.sort_values(by=\"value\", ascending=False)\n",
    "best_10 = df_sorted.head(10)\n",
    "\n",
    "print(tabulate(best_10, headers=\"keys\", tablefmt=\"psql\"))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "63bde924-4e5f-41a3-9aad-58fa0a9716c5",
   "metadata": {},
   "outputs": [],
   "source": [
    "Primera prueba:\n",
    "|    |   number |    value | datetime_start             | datetime_complete          | duration               |   params_colsample_bytree |   params_gamma |   params_learning_rate |   params_max_depth |   params_min_child_weight |   params_n_estimators |   params_reg_alpha |   params_reg_lambda |   params_scale_pos_weight |   params_subsample | state    |\r\n",
    "|----+----------+----------+----------------------------+----------------------------+------------------------+---------------------------+----------------+------------------------+--------------------+---------------------------+-----------------------+--------------------+---------------------+---------------------------+--------------------+----------|\r\n",
    "| 35 |       35 | 0.766467 | 2025-02-23 19:05:51.648664 | 2025-02-23 19:23:42.992309 | 0 days 00:17:51.343645 |                  0.609149 |        2.79174 |             0.016566   |                  7 |                        14 |                   950 |        2.98383e-07 |         0.000771683 |                   1.7469  |           0.753771 | COMPLETE |\r\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "tfg-py3.12",
   "language": "python",
   "name": "tfg-py3.12"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
